### ISSUE TITLE
Problem to download data

### ISSUE THREAD

**Issue by jeantristanb** [SACGF/cdot_rest#7]
Hi, 
I'm searching file : cdot-0.2.8.refseq.grch37_grch38.json.gz to install server, do you knwo where I can find for refseq and ensembl
do you know where I can find file ? 
thank you

**Comment by davmlaw** [comment]
Hi this repo (cdot_rest) is for the REST server, cdot data is at the cdot project:

https://github.com/SACGF/cdot/releases

You should always use the latest version as it will have the most transcripts
